name: dignify
description: A new Flutter project.
publish_to: "none"
version: 0.3.1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  google_nav_bar: ^5.0.6
  get: ^4.6.6
  cloud_firestore: ^4.16.0
  http: ^1.2.1
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  file_picker: ^8.0.7
  path_provider: ^2.1.4
  image: ^4.2.0
  image_picker: ^1.1.2
  mime: ^1.0.6
  http_parser: ^4.0.2
  audioplayers: ^6.1.0
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/splash.jpg
    - assets/images/cover1.png
    - assets/images/cover2.png
    - assets/images/login1.png
    - assets/images/loginlogo.png
    - assets/images/login_background.jpg

flutter_native_splash:
  color: "#000000"
  image: assets/images/splash.jpg
  fullscreen: true

  android_12:
    image: assets/images/splash.jpg
    color: "#000000"
    fullscreen: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
