// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB3In-LeEQ0cBikazTxe36FA_RBCTeR60',
    appId: '1:271947096756:web:7a862b57ad0aae5f162de1',
    messagingSenderId: '271947096756',
    projectId: 'dignify-ipd-project',
    authDomain: 'dignify-ipd-project.firebaseapp.com',
    storageBucket: 'dignify-ipd-project.appspot.com',
    measurementId: 'G-DKL9MKD3HG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVGmTo5cnlJ_Qk0eJ1nuDif_oLnI8CgS0',
    appId: '1:271947096756:android:b1545c59727a22ab162de1',
    messagingSenderId: '271947096756',
    projectId: 'dignify-ipd-project',
    storageBucket: 'dignify-ipd-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM0ksFtqxkjuYVcXv4cSqJkLuw_vT5vcQ',
    appId: '1:271947096756:ios:e3e4f15ab2467c20162de1',
    messagingSenderId: '271947096756',
    projectId: 'dignify-ipd-project',
    storageBucket: 'dignify-ipd-project.appspot.com',
    iosBundleId: 'com.example.dignify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM0ksFtqxkjuYVcXv4cSqJkLuw_vT5vcQ',
    appId: '1:271947096756:ios:7bfbbc9897b11668162de1',
    messagingSenderId: '271947096756',
    projectId: 'dignify-ipd-project',
    storageBucket: 'dignify-ipd-project.appspot.com',
    iosBundleId: 'com.example.dignify.RunnerTests',
  );
}
